In [1]:
import pandas as pd
import numpy as np

In [2]:
lyrics_df = pd.read_csv("Song Lyrics After Cleaning.csv", usecols=['artist', 'song name', 'lyrics', 'length', 'Mood'], index_col='song name')
lyrics_df

,artist,lyrics,Mood,length
song name,,,,
Everyday,Elijah Blake,no no i aint ever trap out the bando but oh lo...,1,1835
The Otherside,Elijah Blake,she dont live on planet earth no more she foun...,0,1366
Pinot,Elijah Blake,trippin off that grigio mobbin light low tripp...,1,1691
Shadows & Diamonds,Elijah Blake,i see a midnight panther so gallant and so bra...,0,824
Uno,Elijah Blake,i just want to readi your mind caus ill still ...,0,1095
...,...,...,...,...
Bunnyranch,Adam Green,bind me gag me take me to the bunnyranch peopl...,1,567
Friends of Mine,Adam Green,and we live on borrow time but this headshot p...,1,810
Frozen in Time,Adam Green,frozin in time forev carri that torch for so l...,0,645
I Wanna Die,Adam Green,i want to chose to die and be buri with a rubi...,0,531
Musical Ladders,Adam Green,music ladder lean on mountain bath in white la...,0,506

In [3]:
lyrics_df['length_log'] = np.log(lyrics_df['length'])
lyrics_df = lyrics_df.drop('length', 1)

In [4]:
lyrics_df['artist'] = lyrics_df['artist'].astype('category').cat.codes
lyrics_df

,artist,lyrics,Mood,length_log
song name,,,,
Everyday,2618,no no i aint ever trap out the bando but oh lo...,1,7.514800
The Otherside,2618,she dont live on planet earth no more she foun...,0,7.219642
Pinot,2618,trippin off that grigio mobbin light low tripp...,1,7.433075
Shadows & Diamonds,2618,i see a midnight panther so gallant and so bra...,0,6.714171
Uno,2618,i just want to readi your mind caus ill still ...,0,6.998510
...,...,...,...,...
Bunnyranch,9,bind me gag me take me to the bunnyranch peopl...,1,6.340359
Friends of Mine,9,and we live on borrow time but this headshot p...,1,6.697034
Frozen in Time,9,frozin in time forev carri that torch for so l...,0,6.469250
I Wanna Die,9,i want to chose to die and be buri with a rubi...,0,6.274762
Musical Ladders,9,music ladder lean on mountain bath in white la...,0,6.226537

In [5]:
lyrics_df['Mood'].value_counts()

0    55801
1    53231
Name: Mood, dtype: int64

In [6]:
requires_n = lyrics_df['Mood'].value_counts().min()

negative_mood = lyrics_df[lyrics_df['Mood'] == 0].sample(n=requires_n)
positive_mood = lyrics_df[lyrics_df['Mood'] == 1]

ML_data = pd.concat([negative_mood, positive_mood])

# The frac keyword argument specifies the fraction of rows to return in the random sample, 
# so frac=1 means to return all rows (in random order).
ML_data = ML_data.sample(frac=1)

In [7]:
ML_data

,artist,lyrics,Mood,length_log
song name,,,,
Sleep,7927,i dont feel good i dont sound good i dont look...,1,6.496775
Happy Birthday,8068,i think my friend said i hear footstep i wore ...,0,6.545350
Call Me,2926,after salli came it like we fell apart no more...,0,7.160846
All the Way,6588,seem to matter what i do so im save this 4 you...,0,6.673298
Blame It on Me,5484,and you know exact what they say turn the othe...,0,7.098376
...,...,...,...,...
"Sweet Sue, Just You",2915,everi littl star abov know the one i love swee...,1,6.322565
Say Goodnight,2615,the sun still hangin in the sky and the world ...,0,6.635947
Push Push,6905,broken and push too far ill fold up neat and d...,0,6.799056
The Boy Next Door,5200,the moment i saw him smile i knew he was just ...,0,6.463029
Rubella,7651,im inflam with desir and it spread like wildfi...,1,6.489205

In [8]:
ML_data.to_csv("ML data.csv")